### ISSUE TITLE
Homepage proofreading

### ISSUE THREAD

**Issue by shevchulya** [aavtamon/boating#38]
1. Remove comma after the word "advantage" in the following sentence: "Another ultimate advantage,  is that our rental price includes fuel. You don't need to worry about paying extra money, and you don't need to waste your time getting gas. It is all on us! "
2. Correct the word "things" in the following sentence: "There are many **thigs** that you can do on the lake. "
3. Remove article "a" in the following sentence: "You can just enjoy your time on the boat, you can swim in the nice clean warm lake, or you can even do **a** water tubing! "

**Comment by aavtamon** [comment]
Done.
Please note, that the texts are not really final. Chuck only did a partial review / correction. We would need to revisit some pages, and especially the home page.
