### ISSUE TITLE
Owner's page proofreading

### ISSUE THREAD

**Issue by shevchulya** [aavtamon/boating#39]
1. Remove coma after the word "program" in the following sentence: "What we offer is a unique program, that is significantly different than other web services looking to lease your boat. "
2. Add apostrophe in the word "owners" in the following sentence: When you determine that you will need your boat on a particular day(s), visit our web site (via the **owners** page), and indicate that the boat is not available for public rental."

**Comment by aavtamon** [comment]
Done
