### ISSUE TITLE
My Reservation tab issue

### ISSUE THREAD

**Issue by shevchulya** [aavtamon/boating#41]
When trying to retrieve reservation in My Reservation tab by entering the reservation number and last name combination, the error message pops-up:
"Failed to retieve reservation.
Please correct your confirmation number and/or last name, and try again. If you cannot retrieve your reservation, please give us a call."
1. Go through reservation and payment process
2. Using the reservation number received, input the number and last name used to the fields in My Reservation page. In the performed test the following credentials were used: 
RHGPHTBCBG - for reservation number
Shevchenko - for last name

Same issue occurs in all browsers.

**Comment by aavtamon** [comment]
This is not really a bug report, this is just a statement.
A bug report would have some information that makes it actionable. For instance, the reservation id and the last name that you tried to enter :)

**Comment by shevchulya** [comment]
Thank you for mentioning that, I have updated the bug description, please review.

**Comment by aavtamon** [comment]
Give it a try, it should be fixed now.
